from pathlib import Path

article_html = """
<!DOCTYPE html>
<html>
<head><title>Autonomous Test</title></head>
<body>
<h1>Autonomous Article</h1>
<p>This article was generated by a script.</p>
</body>
</html>
"""

Path("articles").mkdir(exist_ok=True)
Path("articles/autonomous-test.html").write_text(article_html)

print("Article generated.")